### ISSUE TITLE
When I run the following example, the following error occurs

### ISSUE THREAD

**Issue by Liudg002** [sanic-org/sanic-openapi#230]
[2021-05-12 11:42:08 +0800] [99586] [INFO] Goin' Fast @ http://0.0.0.0:12000
[2021-05-12 11:42:08 +0800] [99586] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "/Users//.conda/envs/HyperDL/lib/python3.7/site-packages/sanic/app.py", line 918, in run
    serve_single(server_settings)
  File "/Users/xxx/.conda/envs/HyperDL/lib/python3.7/site-packages/sanic/server.py", line 725, in serve_single
    serve(**server_settings)
  File "/Users/xxx/.conda/envs/HyperDL/lib/python3.7/site-packages/sanic/server.py", line 562, in serve
    trigger_events(after_start, loop)
  File "/Users/xxx/.conda/envs/HyperDL/lib/python3.7/site-packages/sanic/server.py", line 352, in trigger_events
    result = event(loop)
  File "/Users/xxx/.conda/envs/HyperDL/lib/python3.7/site-packages/sanic_openapi/openapi2/blueprint.py", line 41, in build_spec
    for blueprint_name, handler in get_blueprinted_routes(app):
  File "/Users/xxx/.conda/envs/HyperDL/lib/python3.7/site-packages/sanic_openapi/utils.py", line 52, in get_blueprinted_routes
    if hasattr(route.handler, "view_class"):
AttributeError: 'Route' object has no attribute 'handler'
Traceback (most recent call last):
  File "/Users/xxx/Desktop/StudyAndWorks/Python/MyStudyTest/HyperDL/server.py", line 37, in <module>
    app.run(host="0.0.0.0", port=12000)
  File "/Users/xxx/.conda/envs/HyperDL/lib/python3.7/site-packages/sanic/app.py", line 918, in run
    serve_single(server_settings)
  File "/Users/xxx/.conda/envs/HyperDL/lib/python3.7/site-packages/sanic/server.py", line 725, in serve_single
    serve(**server_settings)
  File "/Users/xxx/.conda/envs/HyperDL/lib/python3.7/site-packages/sanic/server.py", line 562, in serve
    trigger_events(after_start, loop)
  File "/Users/xxx/.conda/envs/HyperDL/lib/python3.7/site-packages/sanic/server.py", line 352, in trigger_events
    result = event(loop)
  File "/Users/xxx/.conda/envs/HyperDL/lib/python3.7/site-packages/sanic_openapi/openapi2/blueprint.py", line 41, in build_spec
    for blueprint_name, handler in get_blueprinted_routes(app):
  File "/Users/xxx/.conda/envs/HyperDL/lib/python3.7/site-packages/sanic_openapi/utils.py", line 52, in get_blueprinted_routes
    if hasattr(route.handler, "view_class"):
AttributeError: 'Route' object has no attribute 'handler

Sanic Version: 21.3.4

**Comment by ahopkins** [comment]
Which version of `sanic-openapi` are you using?

**Comment by Liudg002** [comment]
Sanic Version: 21.3.4

**Comment by ahopkins** [comment]
What example? How can I replicate this?

**Comment by artcg** [comment]
Havent had time to look in detail at this, but  the "get_blueprinted_routes" function may be the issue, the chunk of code which is removed here

https://github.com/sanic-org/sanic-openapi/pull/218/commits/17505ed5e93ca20df8e401328245df38993db03c

was aiming to handle that case, however it may have been a misguided solution, definitely open to some better suggestion...
